name: saigoncoins

services:
  # --- NGINX: CỔNG RA VÀO ---
  nginx:
    image: nginx:stable-alpine
    container_name: saigon-nginx
    hostname: saigon-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
  mongodb:
      image: mongo:latest
      container_name: saigon-mongodb
      hostname: saigon-mongodb
      volumes:
        - mongo_data:/data/db
        - ../../backup_data:/data/backup:ro
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile # Đảm bảo đường dẫn này đúng với file Dockerfile của bạn
    container_name: saigon-backend
    hostname: saigon-backend
    # ports:
    #   - "7000:7000"
    environment:
      # Sửa lại kết nối trực tiếp đến service mongodb bên trong mạng Docker
      - MONGO_URI=mongodb://saigon-mongodb:27017/SaigonCoins
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    container_name: saigon-frontend
    hostname: saigon-frontend
    expose:
      - "3000"
    # ports:
    #   - "3001:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  mongo_data: