server {
    listen 80;

    # Hỗ trợ các file hệ thống của Next.js (Sửa lỗi vỡ giao diện)
    location /_next/ {
        proxy_pass http://saigon_frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }

    # Điều hướng API (Sửa lỗi 404 DB)
    location /api/ {
        proxy_pass http://saigon_backend:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Trang chính
    location / {
        proxy_pass http://saigon_frontend:3000;
        proxy_set_header Host $host;
    }
}